### ISSUE TITLE
New Ape wishing to learn quant skills

### ISSUE THREAD

**Issue by PenguCodes** [HomeDepotHanksApeGang/requests#4]
**Link to your reddit username**
To help us verify requests please submit your reddit username here.

My reddit username is PenguinRPG.

**Propose your question or request**
A clear and concise description of your question or request.

My question or request would be to see the code and ask questions, i am extremely new at coding or quant analysis but i have a background in finance, econ and math and im very interested in learning quant skills, especially from fellow apes.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or questions you've considered that are related to this request.

If i get denied... i guess i will try youtube? Idk, i just want to learn.

**Additional context**
Add any other context or screenshots about the request here.

![download](https://user-images.githubusercontent.com/85531820/121106063-44216c00-c7d3-11eb-9b66-4c151985ee1e.jpg)

**Comment by IvoryPetal** [comment]
A link to the group was sent to your Reddit user account. Thanks and hope to see you soon!
