### ISSUE TITLE
New Entry

### ISSUE THREAD

**Issue by morgan1776** [HomeDepotHanksApeGang/requests#6]
**Link to your reddit username**
To help us verify requests please submit your reddit username here.
**Climbaroc**

**Propose your question or request**
A clear and concise description of your question or request.
Im an engineer who would like to be apart of solving this problem 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or questions you've considered that are related to this request.

**Additional context**
Add any other context or screenshots about the request here.

**Comment by sudoshu** [comment]
Link to the group was sent to your reddit account. Hope to see you soon!
