### ISSUE TITLE
Hank Big Bang - Help Solicitation - Chaosdne

### ISSUE THREAD

**Issue by chaosdne** [HomeDepotHanksApeGang/requests#8]
**Link to your reddit username**
To help us verify requests please submit your reddit username here.
u/chaosdne

**Propose your question or request**
I want to help with the effort. 

I have loaded the [FTD Information available from SEC](https://www.sec.gov/data/foiadocsfailsdatahtm) through DEC 2020 so far. I put it in a SQLite db. The data can be verified by:
`Select FILENAME,count(*)  AS COUNT, Sum(QUANTITY_FAILS) as SumFails
		from FTD 
		group by FILENAME 
		`
The _Trailer record count_  and  _Trailer total quantity of shares_ can be found at the end of any given file from the source linked above. 

i wanted to demonstrate my skillset, and express my openness to helping this group do what you do. 

**Describe alternatives you've considered**
My alternate choice was actually my first choice, so let me go ahead and apologize to u/sudoshu for a complete massacre of a reddit chat.  i talked to my self for a good five minutes, then realized what that my have done to his/her/their email.  so my alternate approach sucked.
 
**Additional context**
i was inspired to make the sec data so that i could play around with it. Specifically, i thought it would be interesting to see how long its been since any given ticker had **not** been on the list. i thought i as started going back more an more tickers wouldn't qualify, and i could create a subset with the longest FTD streak. Then i was going to look to see what that set of tickers said to me.   
Spoiler alert. i am still listening and haven't received a reply. 

I learned of this effort via the Hank Big band quant post. 
[GMEdata.db.zip](https://github.com/SuperstonkQuants/requests/files/6635460/GMEdata.db.zip)

**Comment by xpurplexamyx** [comment]
Howdy, thanks for reaching out! I've sent you a message on reddit with an invite link to the discord :) Come, join us, be merry.
